name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    type: [core-repo-push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - id: cache
        name: Yarn Cache Dir
        run: echo "::set-output name=value::$(yarn cache dir)"

      - name: Restore Lockfile
        uses: actions/cache@v2
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
          restore-keys: yarn-lock-

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache.outputs.value }}
          key: yarn-cache-${{ github.sha }}
          restore-keys: yarn-cache-

      - name: Install
        run: yarn

      - name: Upgrade Core Package
        run: yarn upgrade insane-mc
      
      - name: Clone Core Repo
        uses: actions/checkout@v3
        with:
          repository: insane-mc/imc
          path: core-repo

      - name: Copy Docs from Core Repo
        run: |
          mkdir intro/readme-en
          mkdir intro/readme-en/assets
          cp core-repo/README.md intro/readme-en/README.md -f
          cp core-repo/assets/logo.png intro/readme-en/assets/logo.png -f
          cp core-repo/packages/* packages -r -f

      # - name: Copy README.md of Offical Packages
      #   run: |
      #     cp node_modules/insane-mc/packages/* packages -f -r

      - name: Build
        run: yarn build

      - name: Deploy
        if: ${{ github.repository == 'insane-mc/docs' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vuepress/dist
          publish_branch: pages
          force_orphan: true
